name: CI
on:
  push:
    branches: 'develop'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "23.8.0"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "23.8.0"
      - name: Install dependencies
        run: npm ci
      - name: Build for E2E tests
        run: npm run build
      - name: E2E tests
        run: npm run test:e2e

  merge_develop_into_main:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - e2e-tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git user
        run: |
          git config --global user.email "cd@yopmail.com"
          git config --global user.name "Github CD"
      - name: Merge develop into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/develop --allow-unrelated-histories
          git push origin main