name: CI
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
          install-chromedriver: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "23.8.0"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test:unit
      - name: E2E tests
        run: npm run test:e2e -- --env chrome