name: CI
on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "23.8.0"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "23.8.0"
      - name: Install dependencies
        run: npm ci
      - name: Build for E2E tests
        run: npm run build
      - name: E2E tests
        run: npm run test:e2e

  auto-merge-dependabot:
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: 
      - unit-tests
      - e2e-tests
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "dependabot[bot]"
          git config --global user.email "dependabot[bot]@users.noreply.github.com"
      - name: Merge Dependabot PR
        run: gh pr merge $PR_NUMBER --merge --delete-branch
        env:
          PR_NUMBER: ${{github.event.pull_request.number}}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Merge develop into main
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git merge origin/develop
          git push origin main
