name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "23.8.0"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "23.8.0"
      - name: Install dependencies
        run: npm ci
      - name: Build for E2E tests
        run: npm run build
      - name: E2E tests
        run: npm run test:e2e

  auto-merge:
    runs-on: ubuntu-latest
    needs: 
      - unit-tests
      - e2e-tests
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Auto-merge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
